DOP.Web/DOP.Web/ViewModels/StartPageViewModel.cs
using DOP.Common.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DOP.Web.ViewModels
{
    public class StartPageViewModel
    {
        public List<Department> Departments { get; set; }
        public List<Personnel> Personnel { get; set; }        
    }
}

DOP.Web/DOP.Web/Controllers/MainController.cs
using DOP.Bussines.Providers;
using DOP.Bussines.Search;
using DOP.Web.ViewModels;
using System;
using System.Web.Mvc;

namespace DOP.Web.Controllers
{
    public class MainController : Controller
    {
        private IDOPProvider provider;
        private IDOPSearch test;
        public MainController( IDOPProvider provider,IDOPSearch test)
        {
            this.provider = provider;
            this.test = test;     
        }
        
        public ActionResult StartPage(int? id)
        {
            if (id != null)
            {
                ViewBag.SelectedId = id;
                return View(new StartPageViewModel()
                {
                    Departments = provider.GetAllDepartments(),
                    Personnel = provider.GetPersonnelByDepartmentId((int)id),
                });
            }
            else
            {
                ViewBag.SelectedId = id;
                return View(new StartPageViewModel()
                {
                    Departments = provider.GetAllDepartments(),
                    Personnel = provider.GetAllPersonnel(),
                });
            }
        }
        public ActionResult PersonnelDetails(int PersonnelId)
        {
            return View(provider.GetPersonnelById(PersonnelId));            
        }
    }
}

DOP.Web/DOP.Web/Controllers/SearchController.cs
using DOP.Bussines.Providers;
using DOP.Bussines.Search;
using System.Web.Mvc;

namespace DOP.Web.Controllers
{
    public class SearchController : Controller
    {
        private IDOPProvider provider;
        private IDOPSearch searcher;    
        public SearchController(IDOPProvider provider,IDOPSearch searcher)
        {
            this.provider = provider;
            this.searcher = searcher;
        }
        public ActionResult SearchPage()
        {            
            return View();
        }
        public ActionResult SearchPersonnelByLNM(string LNM)
        {
            return PartialView("~/Views/PartialViews/PersonnelPartialView.cshtml", searcher.SearchPersonnels(LNM, provider.GetAllPersonnel()));
        }
    }
}

DOP.Web/DOP.Web/Views/Main/PersonnelDetails.cshtml
@model DOP.Common.Models.Personnel
@{
    ViewBag.Title = "PersonnelDetails";
}

<h2>Name:@Model.Name</h2>
<h2>Last name:@Model.LastName</h2>
<h2>Middle name:@Model.MiddleName</h2>
<h2>Adress:@Model.Adress</h2>
<h2>Family state:@if (Model.FamilyState == true)
{ <text>+</text>}
else {<text>-</text> }</h2>

DOP.Web/DOP.Web/Views/Main/StartPage.cshtml
@model DOP.Web.ViewModels.StartPageViewModel
@{
    ViewBag.Title = "StartPage";
}
<div class="container navbar-fixed-top" style="width: 10vw;margin-left:0;top:inherit">
    <div class="list-group">
        @{
            foreach (var item in Model.Departments)
            {
                if (ViewBag.SelectedId == item.DepartmentId)
                {
                    <a href='@Url.Action("StartPage", "Main", new { id = item.DepartmentId })' ; class="list-group-item active">@item.Name</a> 
                }
                else
                {
                    <a href='@Url.Action("StartPage", "Main", new { id = item.DepartmentId })' ; class="list-group-item">@item.Name</a> 
                }
            }
        }
        <a href='@Url.Action("SearchPage", "Search")' ; class="list-group-item">Search page</a>
    </div>
</div>
@{Html.RenderPartial("~/Views/PartialViews/PersonnelPartialView.cshtml", Model.Personnel);}

DOP.Web/DOP.Web/Views/PartialViews/PersonnelPartialView.cshtml
@model List<DOP.Common.Models.Personnel>
<table border="1" width="100%" cellpadding="5">
    <tr>
        <th>Name</th>
        <th>Last Name</th>
        <th>Middle Name</th>
    </tr>
    @{ foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.LastName</td>
                <td>@item.MiddleName</td>
                <td>@Html.ActionLink("Details", "PersonnelDetails", "Main", routeValues: new { PersonnelId = item.PersonnelId }, htmlAttributes: null)</td>
            </tr>
        }
    }
</table>

DOP.Web/DOP.Web/Views/Search/SearchPage.cshtml
@{
    ViewBag.Title = "SearchPage";
}

<center><div class="form-group">
    <label for="usr">Name:</label>
    <input type="text" class="form-control" id="usr">
</div>
<div class="form-group">
    <label for="Lstname">Last name:</label>
    <input type="text" class="form-control" id="Lstname">
</div>
<div class="form-group">
    <label for="MidlName">Middle name:</label>
    <input type="text" class="form-control" id="MidlName">
</div>
</center>
    <button onclick="OnSearchClick()" type="button" class="btn btn-primary btn-block">Search</button><br>
<div id="Result">
    </div>
<script type="text/javascript">
    function OnSearchClick()
    {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("SearchPersonnelByLNM", "Search")' + "?LNM=" + $("#Lstname").val() + $("#usr").val() + $("#MidlName").val(),
            success: function (data) {
                if (data != '') {                                        
                    $("#Result").html('');
                    $("#Result").append(data);                   
                }
            }
        });
    }   
</script>

DOP.Web/DOP.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>   
   <div class="container body-content">
        @RenderBody()          
       </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>